# Generated by Django 3.2.6 on 2021-08-17 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.comment'),
        ),
    ]
