# Generated by Django 3.2.6 on 2021-08-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20210820_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Working'), (1, 'Reconciliation'), (2, 'Done')], default=0),
        ),
    ]
