# Generated by Django 3.2.6 on 2021-08-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Working'), (1, 'Reconciliation'), (2, 'Done'), (3, 'Deleted')], default=0),
        ),
    ]
