# Generated by Django 3.2.6 on 2021-08-22 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_delete_telegramaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_notify_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего оповещения'),
        ),
    ]
